### ISSUE TITLE
Roman numerals show lvl even if the enchantment has only one possible lvl

### ISSUE THREAD

**Issue by Dronatar** [lukasabbe/bookshelf-inspector#13]
For example:
Vanilla
![image](https://github.com/user-attachments/assets/d075e8e6-9d95-4c91-a7b4-6ea53d5fb980)
Bookshelf Inspector
![image](https://github.com/user-attachments/assets/ba0d3689-af4f-4b39-98c4-9209e30a90d7)

**Comment by lukasabbe** [comment]
oof here i miss stuff, ah it's a small thing. I will throw it in next version.

**Comment by lukasabbe** [comment]
Fixed in 1.21.4 version
