### ISSUE TITLE
Incorrect mod name

### ISSUE THREAD

**Issue by Dronatar** [lukasabbe/bookshelf-inspector#14]
You can easy see it in Mod Menu
![image](https://github.com/user-attachments/assets/ff8173db-119c-4eb5-bbb2-2c34722b979d)
"Bookshelfinspector" --> "Bookshelf Inspector"

**Comment by lukasabbe** [comment]
Easy fix to next version ;)

**Comment by lukasabbe** [comment]
Fixed in 1.21.4 version
