### ISSUE TITLE
Signed Book and Quill can't be translated

### ISSUE THREAD

**Issue by Dronatar** [lukasabbe/bookshelf-inspector#9]
For example:
Book and Quill
![image](https://github.com/user-attachments/assets/a4f61254-92d0-4a85-a05c-a2fca94c188c)
Signed  Book and Quill
![image](https://github.com/user-attachments/assets/7aeee85a-76e8-49b9-a568-f580d9b2b82f)

**Comment by lukasabbe** [comment]
I don't fully understand what you mean. When you make a signed book you need to name it yourself. If you want to name it "book and quill" in ur own language you can, but i don't think i should force the translation

Please tell me if i got anything wrong

**Comment by lukasabbe** [comment]
But how do you get the signed book? Because you need to sign it? don't u?

**Comment by lukasabbe** [comment]
![2024-11-13_21 48 06](https://github.com/user-attachments/assets/63ca7710-dca0-4a91-8fe1-45e3b758c7d7)
Can't sign it without a name for the book

**Comment by lukasabbe** [comment]
![2024-11-13_21 49 03](https://github.com/user-attachments/assets/9dc9d2bd-882e-4dd8-aeec-c7777c85b916)

**Comment by lukasabbe** [comment]
No problem, haha :)
